#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

cd infrastructure
echo "Running terraform fmt ..."
terraform fmt -recursive
echo "Running terraform validate ..."
terraform validate
echo "Running tflint ..."
tflint
echo "All Terraform checks passed."
cd ..

